### PR TITLE
Generate docs using sphinx

### PR DESCRIPTION
**Pull request by phdru**
Used sphinx-apidoc to generate split API docs.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
I'd like to suggest, also, adding to `tox.ini` a sphinx testenv so that the docs can be easily generated.

**Comment by phdru** [comment]
Well, may be later. ReadTheDocs generate docs themselves. Docs at the sqlobject.org site are not yet published from sphinx-generated files; I don't think sphinx-generated docs are ready to be published. The only reason to add such a command is to test docs' syntax. But docs are updated quite infrequently.

**Comment by sigmavirus24** [comment]
Fair enough. I was thinking of people who might want to build/edit the docs locally and not have to create their own virtualenv for it. We can make this a future improvement though.

**Comment by phdru** [comment]
Certainly.

**Comment by sigmavirus24** [comment]
@phdru did you want review on this or someone to merge it for you?

**Comment by phdru** [comment]
@sigmavirus24 The docs require major overhaul. See https://sqlobject.readthedocs.io/en/latest/index.html — doesn't look like your normal Sphinx docs, right? At a minimum the docs need more and better (deeper) Tables of Contents (to show them at the sidebar).

**Comment by phdru** [comment]
Something like this, may be: http://sqlobject.readthedocs.io/en/latest/index.html ? I added a top-level ToC, changed some titles and sections, switched theme to bizstyle.

**Pull request closed without merging**
