### PR TITLE
Convert five statements to augmented assignments

### PR DESCRIPTION
**Pull request by elfring**
Source code like “`var = var + `…” was specified at some places so far.
Please [use augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Description for augmented assignment statements") instead because they are succinct and can be more efficient.

### CODE REVIEW

**Review by phdru — CHANGES_REQUESTED** [review]
Please replace fancy quotes (`“`) with backticks.

**Review by phdru — CHANGES_REQUESTED** [review]
Please use backticks to highlight `MaxdbConnection.sqlAddLimit()` as code.

**Comment by elfring** [comment]
>…  backticks …

* I do usually not use Markdown markup in commit descriptions (and subjects).
* Otherwise: These characters can eventually be used for shell command evaluations (which do not not matter here).

:thought_balloon: Would you like to choose more pleasing commit messages for your final commits?

**Comment by phdru** [comment]
> > …  backticks …
> 
>     * I do usually not use Markdown markup in commit descriptions (and subjects).

Can I ask why? Simple light-weight ASCII-only markup, widely used — every Git hosting understand it.

Well, if you insist then let's gi down to plain ASCII. Please replace your quotes with plain ASCII double quotes (`"`).

>     * Otherwise: These characters can eventually be used for shell command evaluations (which do not not matter here).

Doesn't matter at all.

**Comment by elfring** [comment]
> Please replace your quotes with double quotes (`"`).

:thought_balloon: What does hinder you to accept typographic quotation characters for commit messages?

**Comment by phdru** [comment]
> thought_balloon Would you like to choose more pleasing commit messages for your final commits?

Of course. The trick is in the word "pleasing". For me "pleasing" means:

- ASCII-only;
- Markdown in commit messages;
- reStructuredText in docstrings.

**Comment by phdru** [comment]
> thought_balloon What does hinder you to accept typographic quotation characters for commit messages?

- For international software developed in a English-speaking community I prefer ASCII for everything;
- Personally I avoid Unicode as I don't need it — I speak Russian and English and I (mostly) use ASCII-compatible 8-bit encoding (KOI8-R);
- Typography doesn't matter — we don't print source code, even less commit messages.
- Recent problem with Unicode discovered: https://www.trojansource.codes/ . It was discussed at the python-dev mailing list last week.

**Comment by elfring** [comment]
:thinking:
* Does your feedback mean that you would like to reject this pull request because of your special requirements for commit messages?
* Do I need to take any further adjustments into account so that shown changes can be integrated with a higher probability?

**Comment by phdru** [comment]
> thinking
> 
>     * Does your feedback mean that you would like to reject this pull request because of your special requirements for commit messages?

Well, you made me to document the requirements: c3933b8 . Thank you!

>     * Do I need to take any further adjustments into account so that shown changes can be integrated with a higher probability?

I hope you've ran the test suite and everything passed?

**Comment by elfring** [comment]
> I hope you've ran the test suite

Yes.


>and everything passed?

:thought_balloon: Which test cases would be applicable for the function “MaxdbConnection.sqlAddLimit()”?

**Comment by phdru** [comment]
> > I hope you've ran the test suite
> 
> Yes.

Nice! All is left is to fix the quotes and force-push.

> > and everything passed?
> 
> thought_balloon Which test cases would be applicable for the function “MaxdbConnection.sqlAddLimit()”?

All of them, of course. You just have to install MaxDB, its Python DB API driver and run the test suite with a proper DB URI. ;-)

Well, I do not demand you do it. MySQL, Postgres and SQLite tests are enough.

**Comment by elfring** [comment]
>… You just have to install MaxDB, …

Do you find the proposed adjustment of the function “MaxdbConnection.sqlAddLimit()” reasonable?

**Comment by phdru** [comment]
> Do you find the proposed adjustment of the function “MaxdbConnection.sqlAddLimit()” reasonable?

Thank you for asking! I didn't like it from the beginning but never though about why I don't like it. Now when you asked I see the reason: it's harder to read. Too condensed. Too much logic squeezed into one line. I prefer to make it this way:

        if 'WHERE' in sql:
            sql += ' AND ' + limit
        else:
            sql += 'WHERE ' + limit

**Comment by elfring** [comment]
>Too condensed.

:thought_balloon: Do we present different views for [the usage of conditional expressions](https://docs.python.org/3/reference/expressions.html#conditional-expressions "Documentation") (in combination with “augmented” assignments)?
(Another bit of duplicate source code specifications can eventually be avoided, can't it?)

**Comment by elfring** [comment]
By the way:
:thought_balloon: Would there be a need to adjust [the check for the usage of a key word like “`WHERE`”](https://stackoverflow.com/questions/5319922/python-check-if-word-is-in-a-string "Check if word is in a string") any further?

**Comment by phdru** [comment]
> > Too condensed.
> 
> thought_balloon Do we present different views for [the usage of conditional expressions](https://docs.python.org/3/reference/expressions.html#conditional-expressions) (in combination with “augmented” assignments)?

The URL points to a doc about **syntax** but not about **semantics**. And the semantic of the resulting condensed line is problematic.

> Another bit of duplicate source code specifications can eventually be avoided, can't it?

Why do you care?

**Comment by phdru** [comment]
> By the way: thought_balloon Would there be a need to adjust [the check for the usage of a key word like “`WHERE`”](https://stackoverflow.com/questions/5319922/python-check-if-word-is-in-a-string) any further?

Currently no, but I cannot give any promise for the future.

**Comment by elfring** [comment]
>Currently no, but I cannot give any promise for the future.

Is the discussed check approach generally questionable? :thinking:

**Comment by elfring** [comment]
>Why do you care?

:thought_balloon: It seems that we stumble on different coding style preferences.

**Comment by phdru** [comment]
> > Currently no, but I cannot give any promise for the future.
> 
> Is the discussed check approach generally questionable? thinking

Nop but the very "discussion" is. If you fixed the quotes at the very first day the PR would be applied instantly. For some reasons you decided to go long way. Up to you; I believe I'm a reasonable and patient man and can tolerate you trolling for quite some time.

PS. You don't think I forgot your 1st wave of contributions and "discussions" around them, do you?

**Comment by phdru** [comment]
> thought_balloon It seems that we stumble on different coding style preferences.

Not "we", just you. It's completely your fault. You have to weight your personal preferences before trying to contribute. Once you decided to dive in your personal preferences no longer matter — you must live by the rules of the project you're contributing to.

**Comment by elfring** [comment]
>For some reasons you decided to go long way.

There are special dependencies involved so that this patch review evolved somehow.
* The status for the software component “MaxDB” might trigger further development considerations.
* Is there a need to reduce the source code adjustment to possible changes for two CacheFactory methods (which would be easier to integrate)?

**Comment by phdru** [comment]
Well, the "discussion" is over, everything has been discussed. Time to do real work. How much time do you need to prepare new code, amend commit messages and force push? Is a week enough? I'll wait a week, no problem.

**Comment by phdru** [comment]
Thanks for letting me know! I will wait…

**Comment by phdru** [comment]
Closed for inactivity.

**Pull request closed without merging**
