### PR TITLE
More Minor Py3k fixes 

### PR DESCRIPTION
**Pull request by drnlm**
Another collection of small python 3 compatability fixes.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
I wonder if we should be using the `inspect` module to inspect the functions/modules that we're dealing with here (instead of relying on private attributes).

**Comment by phdru** [comment]
Are they really private? or just system?

**Comment by sigmavirus24** [comment]
I'm not sure what you mean by "or just system?". The convention is that anything preceded by at least one `_` is not safe to be used by third party code. I know people do it anyway, but there's nothing to prevent all of that from breaking in the near term. I'll have to look into inspect to see how to get this information out because I'm rather certain there's a way to do it.

**Comment by phdru** [comment]
I think you're oversimplifying. Attributes with names that start with one underscore are "private", but even that doesn't mean they are not safe for use. Attributes that start with double underscores are protected via name mangling. But dunder attributes (variables and methods with double underscores at both sides) are system attributes. Dunder methods are supposed to be defined by users to be called by Python: thus built-in function `len()` calls method `.__len__()`, and `bool()` calls `__nonzero__` (now `__bool__`) and `__len__`. Dunder attributes are defined by Python and I think they are quite safe; I'm sure they will not change even in Python 4.

**Comment by sigmavirus24** [comment]
Except that those builtin methods prevent the necessity for anyone to ever directly call them because they abstract away the interface to those methods. They *could* change, and `len()`, `bool()`, etc. would continue to working while directly calling `__len__()` or `__nonzero__()` would break.

Further, there are no wrapper methods for these attributes meaning the intention of the authors was for them to be implementation details. Peeking into implementation details is a recipe for disaster. Because they're implementation details its plausible that they could be changed in 3.5, 3.6, or 3.7. Especially since public APIs (like `argparse.ArgumentParser`) have been broken between versions 3.x and 3.y

**Comment by drnlm** [comment]
While it may well be worth exploring using the inspect module at some point, I personally feel it's best to defer looking at that until after we have a reasonable python 3 port.

**Comment by phdru** [comment]
No, dunder methods aren't implementation details. They are thoroughly documented and I cannot imagine a situation Python developers break them. Well, there was some breakage between Py2 and Py3 but GvR and Co promised not to break things further.

Dunder attributes… well, may be they are implementation details, though I inclined to see the double underscores as a signal "I am very much Python-related", not "very much internal, undocumented and fragile, do not rely upon me!"

But of course I don't mind if you find a better way to access them.

**Comment by phdru** [comment]
Has the dust settled? Any addition to the PR?

**Comment by drnlm** [comment]
Nothing more to add from my side.

**Comment by sigmavirus24** [comment]
Yeah, I'll add this to my todo list and figure out how to access these without dunder attributes.

**Pull request merged**
