### PR TITLE
Mark flake8 exception in mysqlconnection

### PR DESCRIPTION
**Pull request by drnlm**
Flag a python 2 only section appropriately for flake8 & python3

### CODE REVIEW

**Comment by phdru** [comment]
AFAIU `# flake8: noqa` makes flake8 to skip the entire file; `# noqa` makes it skip one line. @sigmavirus24, right?

`# flake8: noaq` — misspelled 'noaq'.

**Comment by drnlm** [comment]
Actually, given that this code only applies when using MySQLdb 1.2.1, which, as it predates python 2.5, may not even work with python 2.6, it's perhaps more sensible to just require a more recent version of MySQLdb and remove this logic entirely.

**Comment by phdru** [comment]
Good idea. Even Debian stable now distributes python-mysql 1.2.3.

**Comment by drnlm** [comment]
Created pull request #110

**Pull request closed without merging**
