### PR TITLE
Flake8 fixes

### PR DESCRIPTION
**Pull request by phdru**

### CODE REVIEW

**Comment by sigmavirus24** [comment]
LGTM

**Comment by phdru** [comment]
These are fixes for the simplest problems. There is a lot of boring work yet. For many weeks if not months.

**Comment by sigmavirus24** [comment]
We can create separate issues for each and mark them as low-hanging fruit for new contributors to get their hands dirty with. =)

**Comment by phdru** [comment]
There should to be a way to create issues programmatically. There are currently 42 distinct errors/warnings with the top having 825 lines and the second one 469. Creating 42 issues by hand would be a lot of work.

**Comment by sigmavirus24** [comment]
```py
import github3

gh = github3.login(token=token)
r = gh.repository('sqlobject', 'sqlobject')
for error, filenames in error_codes:
    r.create_issue('[flake8] Fix instances of {0}'.format(error), body='\n'.join('- [ ] {0}'.format(filename) for filename in filenames), labels=['low-hanging-fruit'])
```

Should be approximately correct. I'll have to check the docs for [github3.py](/sigmavirus24/github3.py) because I don't remember of labels takes a list of label names or ids.

**Comment by phdru** [comment]
Thanks, I'll try this.

**Comment by sigmavirus24** [comment]
I'll be happy to take care of it too =P

**Comment by phdru** [comment]
Just sent you a private email.

**Comment by sigmavirus24** [comment]
All but 2 error codes done using

```py
import time

import github3


def errors_from(filename):
    with open(filename, 'r') as fd:
        for line in fd:
            if line.startswith('#'):
                continue
            count, error = line.strip().split(' ')
            yield error, int(count)


def filenames_from(filename):
    with open(filename, 'r') as fd:
        for line in fd:
            so_filename, _ = line.split(':', 1)
            yield so_filename


def issue_kwargs(error_code, files, count):
    body = '\n'.join('- [ ] {0}'.format(f) for f in sorted(set(files)))
    title = '[flake8] Fix {0} instances of {1}'.format(count, error_code)
    labels = ['low-hanging fruit'] if count < 40 else ['help wanted']
    return {'title': title, 'body': body, 'labels': labels}


def create_issues_from(filename):
    gh = github3.login(username='sigmavirus24',
                       password='mysupersecretpassword')
    repository = gh.repository('sqlobject', 'sqlobject')
    for error, count in errors_from(filename):
        kwargs = issue_kwargs(error, filenames_from(error), count)
        issue = repository.create_issue(**kwargs)
        print('Created {0}'.format(issue.html_url))
        time.sleep(0.5)


if __name__ == '__main__':
    create_issues_from('sort-by-lines')
```

GitHub's API prevents people from spamming repositories by creating more than 20 issues too quickly. So I'll be doing the last 2 soon. Any error_code with `< 40` instances was marked as [low-hanging fruit](https://github.com/sqlobject/sqlobject/labels/low-hanging%20fruit). I marked the rest as [help wanted](https://github.com/sqlobject/sqlobject/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22).

**Comment by sigmavirus24** [comment]
Also I'm :+1: merging this and doing PRs as needed instead of doing one large one.

**Comment by phdru** [comment]
Excellent work, thank you very much!

**Comment by sigmavirus24** [comment]
@phdru do you plan to make this a running PR or are you okay with merging separate PRs into master for each of the other issues.

**Comment by phdru** [comment]
I planned to have flake8-fixes as a long-lived branch to be merged to master once. I don't mind to change the plan, though. Do you want to merge more often?

**Comment by sigmavirus24** [comment]
I've had a very poor experience asking new contributors to send pull requests to a branch that isn't populated by default for them by GitHub. Since you're merging master back into flake8-fixes so often, the number of merge commits won't be much different than if we were to merge back into master regularly. We might be able to update each of the issues with detailed instructions but even when I added those, I had bad luck with PRs from new contributors.

**Comment by phdru** [comment]
I didn't merge master — it was branch 2.1 which I merged both to master and to flake8-fixes.

But I don't have any objections about merging f8f back to master. Please do it as often as you feel the need.

**Pull request closed without merging**
